name: strategy_matrix_os

on: 
  push:
    branches:
      - master
    paths:
      - '.github/workflows/myWorkflow_strategy_os.yml'

jobs:
  my-job:
    name: MyJob-test
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Use cmd
      run: |
        which git
        pwd
        echo "hello world" > hello.world
        ls -al
        export -p
        uname -a
    